### ISSUE TITLE
Regarding SPEC CPU 2006 benchmark run issue

### ISSUE THREAD

**Issue by owahidcse99** [ccelio/Speckle#4]
Hi Chris,
I was able to compile cpu 2006 benchmarks using your Speckle scripts. Many thanks for that!
I used ./gen_binaries.sh --compile --copy and found it copied riscv binaries and inputs in "riscv-spec-test" directory. However I could not run it.

Going to $SPEC_DIR where I have installed cpu 2006 benchmarks, I can see compilation created multiple executables for each benchmarks. It seems non-riscv executables are running perfectly fine.
owahid@owahid-Satellite-E45W-C:~/spec/SPEC_CPU2006/benchspec/CPU2006/401.bzip2/exe$ ./bzip2_base.gcc41-64bit ../data/all/input/input.combined 
spec_init
Loading Input Data
Duplicating 13329296 bytes
Input data 67108864 bytes in length
Compressing Input Data, level 5
..............................
.............................
But if I try to run riscv executable using following, I am getting assertion error
owahid@owahid-Satellite-E45W-C:~/spec/SPEC_CPU2006/benchspec/CPU2006/401.bzip2/exe$ spike pk ./bzip2_base.riscv  ../data/all/input/input.combined 
../pk/elf.c:33: assertion failed: !(eh.e_flags & EF_RISCV_RVC)

Alternatively if I use ./gen_binaries.sh --run (I replaced "spike pk -c" with "spike pk" in gen_binaries.sh)then I get the same thing for all the benchmarks.
  spike pk  h264ref_base.riscv -d foreman_test_encoder_baseline.cfg
../pk/elf.c:33: assertion failed: !(eh.e_flags & EF_RISCV_RVC)
~~~Running 471.omnetpp
  spike pk  omnetpp_base.riscv omnetpp.ini
../pk/elf.c:33: assertion failed: !(eh.e_flags & EF_RISCV_RVC)
~~~Running 473.astar
  spike pk  astar_base.riscv lake.cfg
../pk/elf.c:33: assertion failed: !(eh.e_flags & EF_RISCV_RVC)
~~~Running 483.xalancbmk
  spike pk  Xalan_base.riscv -v test.xml xalanc.xsl
../pk/elf.c:33: assertion failed: !(eh.e_flags & EF_RISCV_RVC)

Done!

Googling around shows in elf.c (but I am not sure where to get elf.c)
#ifndef __riscv_compressed
  assert(!(eh.e_flags & EF_RISCV_RVC));
#endif

Could you please help me on that?
Thanks,
owahid

**Comment by ccelio** [comment]
Do some SPEC workloads work? Or do they all fail?

That error message seems to suggest that you're trying to execute RVC (compressed) code, but that the `pk` was not compiled to support RVC, I think.

Did you compile pk using RVC? Did you compile SPEC using RVC? I also can't remember if RVC works in spike by default, or if you have to tell spike that you want it to execute RVC (via the --isa string, if I remember correctly).

------------

I should also mention, for full disclosure, that executing SPEC workloads in RISC-V is not expected to work when using the `pk` -- it is not well supported and tends to hit bugs when running serious applications such as SPEC workloads. In the past, I've had about 80% of the SPEC workloads execute successfully, but not 100%. 

For my own workflow, I use Speckle to generate the RISC-V binaries, then I copy the Speckle output (via --copy) into a Linux initramfs image and execute Speckle on top of Linux. It's a painful and unfortunately very manual process.

**Comment by owahidcse99** [comment]
Hi Chris,
Thank you for your reply.
I have 2 riscv toolchain installed. The one is riscv_toolchain that has
riscv64-unknown-elf-gcc
riscv64-unknown-elf-g++
spike 
And the other is full blown riscv_gnu_toolchain that has
riscv64-unknown-elf-gcc, riscv64-unknown-elf-g++ as well as
riscv64-unknown-linux-gnu-gcc, riscv64-unknown-linux-gnu-g++ and riscv64-unknown-linux-gnu-gfortran

The first one was installed as part of boom checkout.

Now, in your gen_binaries.sh at Speckle, it reads riscv.cfg that uses riscv64-unknown-linux-gnu-gcc, riscv64-unknown-linux-gnu-g++ and riscv64-unknown-linux-gnu-gfortran to compile SPEC benchmarks.

First I tried replacing linux-gnu with elf and commented fortran compiler as it was not in riscv_toolchain. In that case only bzip2 compilation passed and the rest failed because they needed fortran; I believe.

So I installed the riscv_gnu_toolchain that has everything and the compilation passed for each of them. All the binary executables were ok but I was having problem with riscv executables where all of them failed (to answer your another question spike uses --isa=RV64IMAFDC by default which is compressed I guess).

Now I replaced linux-gnu with elf (in your riscv.cfg that is read by gen_binaries.sh) and only for bzip2 that does not need fortran, executables were generated and I can run riscv binaries.
*****
owahid@owahid-Satellite-E45W-C:~/spec/SPEC_CPU2006/benchspec/CPU2006/401.bzip2/exe$ spike pk bzip2_base.riscv ../data/all/input/input.combined 
spec_init
Loading Input Data
Duplicating 13329296 bytes
Input data 67108864 bytes in length
Compressing Input Data, level 5
Compressed data 15115419 bytes in length
Uncompressing Data
Uncompressed data 67108864 bytes in length
*******
So the question I would like to ask is there any riscv64-unknown-elf-gfortran which was missing in riscv_toolchain that I installed during rocket chip + boom installation?

Otherwise I have to build riscv based linux kernel which would require more tedious tasks.

Thanks,
owahid

**Comment by owahidcse99** [comment]
Hi Chris,

I was wondering is there any riscv64-unknown-elf-gfortran compiler? I did not find it in riscv-toolchain that I installed as part of rocket+boom installation.

I found similar riscv64-unknown-linux-gnu-gfortran in riscv-gnu-toolchain as a separate installation to compile SPEC benchmarks which was needed by your Speckle script gen_binaries.sh. But the riscv executable were not working by Spike, as Spike came through riscv-toolchain that requires programs to be compiled by *-elf-gcc/g++ (and gfortran was not there).

Any thoughts are appreciated.

Thanks,
owahid

**Comment by ccelio** [comment]
Yes, looking through my own RISC-V installation, I see there is a `riscv64-unknown-linux-gnu-gfortran`.  I have no experience using gfortran, but I assume (like the other linux-gnu* tools) it is compiling code dynamically and will need to be run on top of Linux to work properly.

You can try compiling it statically, although since using `pk` is not supported for running SPEC, I actually recommend you run your SPEC workloads in Linux.

**Comment by owahidcse99** [comment]
Hi Chris,
I was trying to cross compile Linux for RISCV so I can run the SPEC benchmarks. I did the following but it it is giving me following error.
git clone https://github.com/riscv/riscv-linux.git linux-3.14.33
curl -L https://www.kernel.org/pub/linux/kernel/v3.x/linux-3.14.33.tar.xz | tar -xJ
make ARCH=riscv defconfig
owahid@owahid-Satellite-E45W-C:~/boom-rocket/rocket-chip/riscv-tools/linux-3.14.33$ make -j2 ARCH=riscv
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  CC      scripts/mod/empty.o
riscv64-unknown-linux-gnu-gcc: error: unrecognized command line option '-mabi=lp64'
scripts/Makefile.build:308: recipe for target 'scripts/mod/empty.o' failed
make[2]: *** [scripts/mod/empty.o] Error 1
It seems, riscv64-unknown-linux-gnu-gcc cannot take this -mabi option.
Any suggestion?
Thanks,
owahid

**Comment by ccelio** [comment]
If gcc doesn't accept the `-mabi=lp64` argument, then it doesn't accept that argument.  That version of riscv-linux looks quite old -- shouldn't you be using linux 4.6?

**Comment by owahidcse99** [comment]
Yes, I did it for Linux 4.6.2 as well. It is still the same.

**Comment by owahidcse99** [comment]
https://riscv.org/software-tools/linux/

**Comment by ccelio** [comment]
You'll need to change the compiler flags being fed to gcc then. Your version of riscv-linux may be out of sync with riscv-tools. The abi arguments to riscv*gcc may have changed.

**Comment by owahidcse99** [comment]
Thanks a lot! Updating riscv-linux worked. Thanks again.
