### ISSUE TITLE
416.gamess requires -funconstrained-commons

### ISSUE THREAD

**Issue by aswaterman** [ccelio/Speckle#6]
This issue is just for bookkeeping; I'm not sure where else to put it.  The benchmark is buggy and it fails with recent GCCs on other platforms, too: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69368

**Comment by aswaterman** [comment]
-funconstrained-commons is a relatively new flag.  For very old GCCs, -fno-aggressive-loop-optimizations seems to suffice.  For GCCs in the middle, I don't have a good workaround.

**Comment by ccelio** [comment]
Thanks, if you find the flag(s) that works for RISC-V tools, those flags should be placed in the portability section of the configuration files: https://github.com/ccelio/Speckle/blob/master/riscv.cfg#L134

They can then sit in the corner with perlbench's `std=gnu89` and think about what they did.
